### ISSUE TITLE
NCTU-Oauth Support to Flask

### ISSUE THREAD

**Issue by steven5538** [NCTU-OAuth/services#1]
網站名稱：NCTU-Oauth 0.1.0 : Python Package Index
網址：[https://pypi.python.org/pypi/NCTU-Oauth](https://pypi.python.org/pypi/NCTU-Oauth
) 
簡介：針對 Python Flask 進行開發的套件，讓開發者用 Flask 時可以輕鬆的套用 NCTU-Oauth。

**Comment by kevchentw** [comment]
已加，感謝大大
