### ISSUE TITLE
What is the response of {"error": "access_denied"}

### ISSUE THREAD

**Issue by skhuang** [NCTU-OAuth/services#3]
post to https://id.nctu.edu.tw/o/token with correct code, client_id, and client_secret, only to obtain the response of {"error": "access_denied"}. 

from http://gpe3.acm-icpc.tw/ , app name nctupe.

**Comment by kevchentw** [comment]
如果使用者取消授權的話，目前會回應 ` {"error": "access_denied"}`  
之後會寫進文件

**Comment by skhuang** [comment]
但這是使用者按授權的結果，我們已經取得 code 後，送去取 token 得到的 response。

**Comment by kevchentw** [comment]
在取得 code 後，必須在60秒內去換 token，可以看看是否是過期造成的結果？

**Comment by skhuang** [comment]
找到問題了。post to https://id.nctu.edu.tw/o/token from http://example.com/oauth/
Post 以下資料:

grand_type=authorization_code&code=<Code>&client_id=<Client_id>&client_secret=<Client_secret>&redirect_uri=<URL>

其中 <Code> 是 http://example.com/oauth/?<Code> 傳來。<Client_id>, <Client_secret> 都是由id.nctu.edu.tw 取得。問題出在 <URL>。

我誤解了 <URL> 。我以為是授權後，將導過去的首頁。但這邊要求的是 http://example.com/oauth。
也就是設定在 id.nctu.edu.tw 的 Redirect uris。

這個 redirect_uri 多餘、又誤導。因為被執行的 URI 就是 redirect_uri，根本不需要。不然，文件就寫清楚，就是那個 htp://example.com/oauth:

把文件寫明:
 redirect_uri 就是欲串接平台對應接收 OAuth 參數之網址

**Comment by skhuang** [comment]
建議文件修改如下:
--------------------------
1. 透過 POST 方式 https://id.nctu.edu.tw/o/token/， form-data 包含以下資料

grant_type: authorization_code
code: <Code>
client_id:<Client id>
client_secret: <Client Secret>
redirect_uri: 就是欲串接平台對應接收 OAuth 參數之網址, 此例為 http://example.com/oauth/
